// ---------------------------------------------------------------------------
// src/dashboard/server.js
//
// Web dashboard server — serves on DASHBOARD_PORT (default 3003)
// Authentication via signed tokens generated by /dashboard token command
// ---------------------------------------------------------------------------

const http     = require('http');
const fs       = require('fs');
const path     = require('path');
const crypto   = require('crypto');


const DASHBOARD_PORT   = parseInt(process.env.DASHBOARD_PORT || '3003', 10);
const DASHBOARD_SECRET = process.env.DASHBOARD_SECRET || null;

// In-memory session store: token → { userId, username, expires }
const sessions = new Map();
// Single-use login tokens: token → { userId, username, expires }
const loginTokens = new Map();

// ---------------------------------------------------------------------------
// Token utilities
// ---------------------------------------------------------------------------

function generateToken(length = 32) {
  return crypto.randomBytes(length).toString('hex');
}

function signToken(token) {
  if (!DASHBOARD_SECRET) return token;
  const hmac = crypto.createHmac('sha256', DASHBOARD_SECRET);
  hmac.update(token);
  return `${token}.${hmac.digest('hex')}`;
}

function verifyToken(signed) {
  if (!DASHBOARD_SECRET) return signed;
  const [token, sig] = signed.split('.');
  if (!token || !sig) return null;
  const expected = crypto.createHmac('sha256', DASHBOARD_SECRET)
    .update(token).digest('hex');
  if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return null;
  return token;
}

/**
 * Create a single-use login token for a Haven user.
 * Called by the /dashboard token slash command.
 */
function createLoginToken(userId, username) {
  const raw     = generateToken(24);
  const signed  = signToken(raw);
  const expires = Date.now() + 24 * 60 * 60 * 1000; // 24h
  loginTokens.set(raw, { userId, username, expires });
  return signed;
}

/**
 * Exchange a login token for a session cookie.
 * Single-use — token is deleted after use.
 */
function redeemLoginToken(signed) {
  const raw = verifyToken(signed);
  if (!raw) return null;
  const entry = loginTokens.get(raw);
  if (!entry) return null;
  if (Date.now() > entry.expires) {
    loginTokens.delete(raw);
    return null;
  }
  loginTokens.delete(raw); // single-use
  const sessionToken  = generateToken(32);
  const sessionSigned = signToken(sessionToken);
  sessions.set(sessionToken, {
    userId:   entry.userId,
    username: entry.username,
    expires:  Date.now() + 24 * 60 * 60 * 1000,
  });
  return sessionSigned;
}

/**
 * Validate a session cookie. Returns session data or null.
 */
function validateSession(cookieHeader) {
  if (!cookieHeader) return null;
  const match = cookieHeader.match(/dashboard_session=([^;]+)/);
  if (!match) return null;
  const signed = decodeURIComponent(match[1]);
  const raw    = verifyToken(signed);
  if (!raw) return null;
  const session = sessions.get(raw);
  if (!session) return null;
  if (Date.now() > session.expires) {
    sessions.delete(raw);
    return null;
  }
  return session;
}

// ---------------------------------------------------------------------------
// API handlers
// ---------------------------------------------------------------------------

function getApiData(pathname, session, bot, channelManager) {
  const { calendar, users, rssFeeds, admins, modLogs, bans } = require('../database');

  if (pathname === '/api/status') {
    const allChannels = channelManager.getAllTokens();
    return {
      botName:   process.env.BOT_NAME || 'HavenBot',
      channels:  allChannels.length,
      channelList: allChannels.map(c => ({
        name: c.channelName, code: c.channelCode, source: c.source
      })),
      uptime:    Math.floor(process.uptime()),
      timezone:  process.env.TIMEZONE || 'UTC',
      agentEnabled: (process.env.AGENT_ENABLED || 'false').toLowerCase() === 'true',
      agentName: process.env.AGENT_NAME || 'Bob',
    };
  }

  if (pathname === '/api/calendar') {
    const events = calendar.getUpcoming(50);
    return { events };
  }

  if (pathname === '/api/rss') {
    const feeds = rssFeeds.getAll();
    return {
      feeds: feeds.map(f => ({
        ...f,
        channelName: channelManager.getChannelName(f.channel_id) || f.channel_id,
      }))
    };
  }

  if (pathname === '/api/modlog') {
    const logs = modLogs.getAll(50);
    return { logs };
  }

  if (pathname === '/api/leaderboard') {
    const top = users.getLeaderboard ? users.getLeaderboard(20) : [];
    return { users: top };
  }

  if (pathname === '/api/channels') {
    const all = channelManager.getAllTokens();
    return {
      channels: all.map(c => ({
        name: c.channelName, code: c.channelCode, source: c.source
      }))
    };
  }

  return null;
}

// ---------------------------------------------------------------------------
// Static file server
// ---------------------------------------------------------------------------

const MIME_TYPES = {
  '.html': 'text/html',
  '.css':  'text/css',
  '.js':   'application/javascript',
  '.json': 'application/json',
  '.png':  'image/png',
  '.ico':  'image/x-icon',
  '.svg':  'image/svg+xml',
};

function serveStatic(res, filePath) {
  const ext  = path.extname(filePath);
  const mime = MIME_TYPES[ext] || 'text/plain';
  try {
    const content = fs.readFileSync(filePath);
    res.writeHead(200, { 'Content-Type': mime });
    res.end(content);
  } catch {
    res.writeHead(404);
    res.end('Not found');
  }
}

// ---------------------------------------------------------------------------
// Main server
// ---------------------------------------------------------------------------

function startDashboard(bot, channelManager) {
  if (!DASHBOARD_SECRET) {
    console.warn('⚠️  Dashboard disabled — DASHBOARD_SECRET not set in .env');
    console.warn('   Generate one with: openssl rand -base64 48');
    return null;
  }

  const staticDir = path.join(__dirname, 'public');

  const server = http.createServer(async (req, res) => {
    const reqUrl   = new URL(req.url, 'http://localhost');
    const pathname = reqUrl.pathname;
    const method   = req.method;

    // CORS headers for local dev
    res.setHeader('X-Content-Type-Options', 'nosniff');

    // --- Login token exchange ---
    if (pathname === '/auth/login' && method === 'POST') {
      let body = '';
      req.on('data', c => body += c);
      req.on('end', () => {
        try {
          const { token } = JSON.parse(body);
          const sessionSigned = redeemLoginToken(token);
          if (!sessionSigned) {
            res.writeHead(401, { 'Content-Type': 'application/json' });
            return res.end(JSON.stringify({ error: 'Invalid or expired token' }));
          }
          res.writeHead(200, {
            'Content-Type': 'application/json',
            'Set-Cookie': `dashboard_session=${encodeURIComponent(sessionSigned)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400`,
          });
          res.end(JSON.stringify({ ok: true }));
        } catch {
          res.writeHead(400);
          res.end('Bad request');
        }
      });
      return;
    }

    // --- Logout ---
    if (pathname === '/auth/logout' && method === 'POST') {
      res.writeHead(200, {
        'Content-Type': 'application/json',
        'Set-Cookie': 'dashboard_session=; HttpOnly; Path=/; Max-Age=0',
      });
      return res.end(JSON.stringify({ ok: true }));
    }

    // --- API routes (require auth) ---
    if (pathname.startsWith('/api/')) {
      const session = validateSession(req.headers.cookie);
      if (!session) {
        res.writeHead(401, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: 'Unauthorized' }));
      }
      const data = getApiData(pathname, session, bot, channelManager);
      if (data === null) {
        res.writeHead(404, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: 'Not found' }));
      }
      res.writeHead(200, { 'Content-Type': 'application/json' });
      return res.end(JSON.stringify(data));
    }

    // --- Static files ---
    // Serve login page without auth
    if (pathname === '/' || pathname === '/login') {
      const session = validateSession(req.headers.cookie);
      if (session && pathname === '/login') {
        res.writeHead(302, { Location: '/dashboard' });
        return res.end();
      }
      if (!session && pathname !== '/login') {
        res.writeHead(302, { Location: '/login' });
        return res.end();
      }
      return serveStatic(res, path.join(staticDir, pathname === '/login' ? 'login.html' : 'index.html'));
    }

    // All other routes require auth
    const session = validateSession(req.headers.cookie);
    if (!session) {
      res.writeHead(302, { Location: '/login' });
      return res.end();
    }

    // Serve dashboard pages
    if (pathname === '/dashboard' || pathname === '/dashboard/') {
      return serveStatic(res, path.join(staticDir, 'index.html'));
    }

    // Serve static assets
    const filePath = path.join(staticDir, pathname.replace(/^\//, ''));
    serveStatic(res, filePath);
  });

  server.listen(DASHBOARD_PORT, () => {
    console.log(`🌐 Dashboard running at http://localhost:${DASHBOARD_PORT}`);
  });

  return server;
}

module.exports = { startDashboard, createLoginToken };
