// ---------------------------------------------------------------------------
// src/dashboard/server.js
//
// Web dashboard server — serves on DASHBOARD_PORT (default 3003)
// Authentication via signed tokens generated by /dashboard token command
// ---------------------------------------------------------------------------

const http     = require('http');
const https    = require('https');
const fs       = require('fs');
const path     = require('path');
const crypto   = require('crypto');


const DASHBOARD_PORT   = parseInt(process.env.DASHBOARD_PORT || '3003', 10);
const DASHBOARD_SECRET = process.env.DASHBOARD_SECRET || null;

// In-memory session store: token → { userId, username, expires }
const sessions = new Map();
// Single-use login tokens: token → { userId, username, expires }
const loginTokens = new Map();

// ---------------------------------------------------------------------------
// Token utilities
// ---------------------------------------------------------------------------

function generateToken(length = 32) {
  return crypto.randomBytes(length).toString('hex');
}

function signToken(token) {
  if (!DASHBOARD_SECRET) return token;
  const hmac = crypto.createHmac('sha256', DASHBOARD_SECRET);
  hmac.update(token);
  return `${token}.${hmac.digest('hex')}`;
}

function verifyToken(signed) {
  if (!DASHBOARD_SECRET) return signed;
  const [token, sig] = signed.split('.');
  if (!token || !sig) return null;
  const expected = crypto.createHmac('sha256', DASHBOARD_SECRET)
    .update(token).digest('hex');
  if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return null;
  return token;
}

/**
 * Create a single-use login token for a Haven user.
 * Called by the /dashboard token slash command.
 */
function createLoginToken(userId, username) {
  const raw     = generateToken(24);
  const signed  = signToken(raw);
  const expires = Date.now() + 24 * 60 * 60 * 1000; // 24h
  loginTokens.set(raw, { userId, username, expires });
  return signed;
}

/**
 * Exchange a login token for a session cookie.
 * Single-use — token is deleted after use.
 */
function redeemLoginToken(signed) {
  const raw = verifyToken(signed);
  if (!raw) return null;
  const entry = loginTokens.get(raw);
  if (!entry) return null;
  if (Date.now() > entry.expires) {
    loginTokens.delete(raw);
    return null;
  }
  loginTokens.delete(raw); // single-use
  const sessionToken  = generateToken(32);
  const sessionSigned = signToken(sessionToken);
  sessions.set(sessionToken, {
    userId:   entry.userId,
    username: entry.username,
    expires:  Date.now() + 24 * 60 * 60 * 1000,
  });
  return sessionSigned;
}

/**
 * Validate a session cookie. Returns session data or null.
 */
function validateSession(cookieHeader) {
  if (!cookieHeader) return null;
  const match = cookieHeader.match(/dashboard_session=([^;]+)/);
  if (!match) return null;
  const signed = decodeURIComponent(match[1]);
  const raw    = verifyToken(signed);
  if (!raw) return null;
  const session = sessions.get(raw);
  if (!session) return null;
  if (Date.now() > session.expires) {
    sessions.delete(raw);
    return null;
  }
  return session;
}

// ---------------------------------------------------------------------------
// API handlers
// ---------------------------------------------------------------------------

async function getApiData(pathname, session, bot, channelManager) {
  const { calendar, users, rssFeeds, admins, modLogs, bans, db } = require('../database');

  if (pathname === '/api/status') {
    const allChannels = channelManager.getAllTokens();
    return {
      botName:   process.env.BOT_NAME || 'HavenBot',
      channels:  allChannels.length,
      channelList: allChannels.map(c => ({
        name: c.channelName, code: c.channelCode, source: c.source
      })),
      uptime:    Math.floor(process.uptime()),
      timezone:  process.env.TIMEZONE || 'UTC',
      agentEnabled: (process.env.AGENT_ENABLED || 'false').toLowerCase() === 'true',
      agentName: process.env.AGENT_NAME || 'Bob',
    };
  }

  if (pathname === '/api/channels') {
    const all = channelManager.getAllTokens();
    return {
      channels: all.map(c => ({
        name: c.channelName, code: c.channelCode, source: c.source
      }))
    };
  }

  if (pathname === '/api/modlog') {
    const logs = modLogs.getAll(50);
    return { logs };
  }

  if (pathname === '/api/users') {
    const top     = users.getLeaderboard(50);
    const total   = db.prepare('SELECT COUNT(*) as c FROM users').get();
    const totalXp = db.prepare('SELECT SUM(xp) as x FROM users').get();
    const achiev  = db.prepare('SELECT COUNT(*) as c FROM user_achievements').get();
    return {
      leaderboard: top,
      totalUsers:  total?.c || 0,
      totalXp:     totalXp?.x || 0,
      totalAchievements: achiev?.c || 0,
    };
  }

  if (pathname === '/api/calendar') {
    const events = calendar.getUpcoming(50);
    // Enrich with notification status
    const enriched = events.map(e => {
      const notifs = db.prepare(
        'SELECT * FROM event_notifications WHERE event_id = ? ORDER BY notify_at'
      ).all(e.id);
      const rsvps = calendar.getRsvps(e.id);
      return { ...e, notifications: notifs, rsvpCount: rsvps.length };
    });
    return { events: enriched };
  }

  if (pathname === '/api/rss') {
    const feeds = rssFeeds.getAll();
    return {
      feeds: feeds.map(f => {
        const seenCount = db.prepare('SELECT COUNT(*) as c FROM rss_seen WHERE feed_id = ?').get(f.id);
        const lastItem  = db.prepare('SELECT item_title, seen_at FROM rss_seen WHERE feed_id = ? ORDER BY seen_at DESC LIMIT 1').get(f.id);
        return {
          ...f,
          channelName: channelManager.getChannelName(f.channel_id) || f.channel_id,
          seenCount:   seenCount?.c || 0,
          lastItemTitle: lastItem?.item_title || null,
          lastItemAt:    lastItem?.seen_at    || null,
        };
      })
    };
  }

  if (pathname === '/api/agent') {
    try {
      const agentDb = require('../agent/database').getDb();
      if (!agentDb) return { enabled: false };

      const convCount  = agentDb.prepare('SELECT COUNT(*) as c FROM conversations').get();
      const memCount   = agentDb.prepare('SELECT COUNT(*) as c FROM memory').get();
      const toolCount  = agentDb.prepare('SELECT COUNT(*) as c FROM tool_log').get();
      const toolStats  = agentDb.prepare(
        'SELECT tool_name, COUNT(*) as count FROM tool_log GROUP BY tool_name ORDER BY count DESC'
      ).all();
      const recentTools = agentDb.prepare(
        'SELECT tool_name, arguments, result, timestamp FROM tool_log ORDER BY timestamp DESC LIMIT 20'
      ).all();
      const channelConvs = agentDb.prepare(
        'SELECT channel_id, COUNT(*) as count FROM conversations GROUP BY channel_id ORDER BY count DESC'
      ).all();
      const digestStats = agentDb.prepare('SELECT * FROM rss_digests WHERE active = 1').all();

      return {
        enabled:      true,
        agentName:    process.env.AGENT_NAME || 'Bob',
        model:        process.env.OLLAMA_MODEL || 'unknown',
        ollamaUrl:    process.env.OLLAMA_URL || '',
        searxngUrl:   process.env.SEARXNG_URL || '',
        totalConversations: convCount?.c || 0,
        totalMemories:      memCount?.c  || 0,
        totalToolCalls:     toolCount?.c || 0,
        toolStats,
        recentTools,
        channelConversations: channelConvs.map(c => ({
          channelName: channelManager.getChannelName(c.channel_id) || c.channel_id,
          count: c.count,
        })),
        digests: digestStats,
      };
    } catch {
      return { enabled: false };
    }
  }

  if (pathname === '/api/health') {

    const pingOllama = () => new Promise(resolve => {
      const start = Date.now();
      const url   = new URL('/api/tags', process.env.OLLAMA_URL || 'http://localhost:11434');
      const lib   = url.protocol === 'https:' ? https : http;
      const req   = lib.get(url.toString(), res => {
        res.resume();
        resolve({ ok: res.statusCode === 200, ms: Date.now() - start });
      });
      req.on('error', () => resolve({ ok: false, ms: Date.now() - start }));
      req.setTimeout(3000, () => { req.destroy(); resolve({ ok: false, ms: 3000, error: 'timeout' }); });
    });

    const pingSearxng = () => new Promise(resolve => {
      if (!process.env.SEARXNG_URL) return resolve({ ok: false, disabled: true });
      const start = Date.now();
      const url   = new URL('/search?q=test&format=json', process.env.SEARXNG_URL);
      const lib   = url.protocol === 'https:' ? https : http;
      const req   = lib.get(url.toString(), { headers: { Accept: 'application/json' } }, res => {
        res.resume();
        resolve({ ok: res.statusCode === 200, ms: Date.now() - start });
      });
      req.on('error', () => resolve({ ok: false, ms: Date.now() - start }));
      req.setTimeout(3000, () => { req.destroy(); resolve({ ok: false, ms: 3000, error: 'timeout' }); });
    });

    const [ollama, searxng] = await Promise.all([pingOllama(), pingSearxng()]);
    return {
      ollama: { ...ollama, url: process.env.OLLAMA_URL || 'http://localhost:11434' },
      searxng,
      bot: { ok: true, uptime: Math.floor(process.uptime()) },
    };
  }

  return null;
}

// ---------------------------------------------------------------------------
// Static file server
// ---------------------------------------------------------------------------

const MIME_TYPES = {
  '.html': 'text/html',
  '.css':  'text/css',
  '.js':   'application/javascript',
  '.json': 'application/json',
  '.png':  'image/png',
  '.ico':  'image/x-icon',
  '.svg':  'image/svg+xml',
};

function serveStatic(res, filePath) {
  const ext  = path.extname(filePath);
  const mime = MIME_TYPES[ext] || 'text/plain';
  try {
    const content = fs.readFileSync(filePath);
    res.writeHead(200, { 'Content-Type': mime });
    res.end(content);
  } catch {
    res.writeHead(404);
    res.end('Not found');
  }
}

// ---------------------------------------------------------------------------
// Main server
// ---------------------------------------------------------------------------

function startDashboard(bot, channelManager) {
  if (!DASHBOARD_SECRET) {
    console.warn('⚠️  Dashboard disabled — DASHBOARD_SECRET not set in .env');
    console.warn('   Generate one with: openssl rand -base64 48');
    return null;
  }

  const staticDir = path.join(__dirname, 'public');

  const server = http.createServer(async (req, res) => {
    const reqUrl   = new URL(req.url, 'http://localhost');
    const pathname = reqUrl.pathname;
    const method   = req.method;

    // CORS headers for local dev
    res.setHeader('X-Content-Type-Options', 'nosniff');

    // --- Login token exchange ---
    if (pathname === '/auth/login' && method === 'POST') {
      let body = '';
      req.on('data', c => body += c);
      req.on('end', () => {
        try {
          const { token } = JSON.parse(body);
          const sessionSigned = redeemLoginToken(token);
          if (!sessionSigned) {
            res.writeHead(401, { 'Content-Type': 'application/json' });
            return res.end(JSON.stringify({ error: 'Invalid or expired token' }));
          }
          res.writeHead(200, {
            'Content-Type': 'application/json',
            'Set-Cookie': `dashboard_session=${encodeURIComponent(sessionSigned)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400`,
          });
          res.end(JSON.stringify({ ok: true }));
        } catch {
          res.writeHead(400);
          res.end('Bad request');
        }
      });
      return;
    }

    // --- Logout ---
    if (pathname === '/auth/logout' && method === 'POST') {
      res.writeHead(200, {
        'Content-Type': 'application/json',
        'Set-Cookie': 'dashboard_session=; HttpOnly; Path=/; Max-Age=0',
      });
      return res.end(JSON.stringify({ ok: true }));
    }

    // --- API routes (require auth) ---
    if (pathname.startsWith('/api/')) {
      const session = validateSession(req.headers.cookie);
      if (!session) {
        res.writeHead(401, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: 'Unauthorized' }));
      }
      const data = await getApiData(pathname, session, bot, channelManager);
      if (data === null) {
        res.writeHead(404, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: 'Not found' }));
      }
      res.writeHead(200, { 'Content-Type': 'application/json' });
      return res.end(JSON.stringify(data));
    }

    // --- Static files ---
    // Serve login page without auth
    if (pathname === '/' || pathname === '/login') {
      const session = validateSession(req.headers.cookie);
      if (session && pathname === '/login') {
        res.writeHead(302, { Location: '/dashboard' });
        return res.end();
      }
      if (!session && pathname !== '/login') {
        res.writeHead(302, { Location: '/login' });
        return res.end();
      }
      return serveStatic(res, path.join(staticDir, pathname === '/login' ? 'login.html' : 'index.html'));
    }

    // All other routes require auth
    const session = validateSession(req.headers.cookie);
    if (!session) {
      res.writeHead(302, { Location: '/login' });
      return res.end();
    }

    // Serve dashboard pages
    if (pathname === '/dashboard' || pathname === '/dashboard/') {
      return serveStatic(res, path.join(staticDir, 'index.html'));
    }

    // Serve static assets
    const filePath = path.join(staticDir, pathname.replace(/^\//, ''));
    serveStatic(res, filePath);
  });

  server.listen(DASHBOARD_PORT, () => {
    console.log(`🌐 Dashboard running at http://localhost:${DASHBOARD_PORT}`);
  });

  return server;
}

module.exports = { startDashboard, createLoginToken };
