// ---------------------------------------------------------------------------
// src/dashboard/server.js
//
// Web dashboard server — serves on DASHBOARD_PORT (default 3003)
// Authentication via signed tokens generated by /dashboard token command
// ---------------------------------------------------------------------------

const http     = require('http');
const https    = require('https');
const fs       = require('fs');
const path     = require('path');
const crypto   = require('crypto');


const DASHBOARD_PORT   = parseInt(process.env.DASHBOARD_PORT || '3003', 10);
const DASHBOARD_SECRET = process.env.DASHBOARD_SECRET || null;

// In-memory session store: token → { userId, username, expires }
const sessions = new Map();
// Single-use login tokens: token → { userId, username, expires }
const loginTokens = new Map();

// ---------------------------------------------------------------------------
// Token utilities
// ---------------------------------------------------------------------------

function generateToken(length = 32) {
  return crypto.randomBytes(length).toString('hex');
}

function signToken(token) {
  if (!DASHBOARD_SECRET) return token;
  const hmac = crypto.createHmac('sha256', DASHBOARD_SECRET);
  hmac.update(token);
  return `${token}.${hmac.digest('hex')}`;
}

function verifyToken(signed) {
  if (!DASHBOARD_SECRET) return signed;
  const [token, sig] = signed.split('.');
  if (!token || !sig) return null;
  const expected = crypto.createHmac('sha256', DASHBOARD_SECRET)
    .update(token).digest('hex');
  if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return null;
  return token;
}

/**
 * Create a single-use login token for a Haven user.
 * Called by the /dashboard token slash command.
 */
function createLoginToken(userId, username) {
  const raw     = generateToken(24);
  const signed  = signToken(raw);
  const expires = Date.now() + 24 * 60 * 60 * 1000; // 24h
  loginTokens.set(raw, { userId, username, expires });
  return signed;
}

/**
 * Exchange a login token for a session cookie.
 * Single-use — token is deleted after use.
 */
function redeemLoginToken(signed) {
  const raw = verifyToken(signed);
  if (!raw) return null;
  const entry = loginTokens.get(raw);
  if (!entry) return null;
  if (Date.now() > entry.expires) {
    loginTokens.delete(raw);
    return null;
  }
  loginTokens.delete(raw); // single-use
  const sessionToken  = generateToken(32);
  const sessionSigned = signToken(sessionToken);
  sessions.set(sessionToken, {
    userId:   entry.userId,
    username: entry.username,
    expires:  Date.now() + 24 * 60 * 60 * 1000,
  });
  return sessionSigned;
}

/**
 * Validate a session cookie. Returns session data or null.
 */
function validateSession(cookieHeader) {
  if (!cookieHeader) return null;
  const match = cookieHeader.match(/dashboard_session=([^;]+)/);
  if (!match) return null;
  const signed = decodeURIComponent(match[1]);
  const raw    = verifyToken(signed);
  if (!raw) return null;
  const session = sessions.get(raw);
  if (!session) return null;
  if (Date.now() > session.expires) {
    sessions.delete(raw);
    return null;
  }
  return session;
}

// ---------------------------------------------------------------------------
// API handlers
// ---------------------------------------------------------------------------

async function getApiData(pathname, session, bot, channelManager) {
  const { calendar, users, rssFeeds, admins, modLogs, bans, db } = require('../database');

  if (pathname === '/api/status') {
    const allChannels = channelManager.getAllTokens();
    return {
      botName:   process.env.BOT_NAME || 'HavenBot',
      channels:  allChannels.length,
      channelList: allChannels.map(c => ({
        name: c.channelName, code: c.channelCode, source: c.source
      })),
      uptime:    Math.floor(process.uptime()),
      timezone:  process.env.TIMEZONE || 'UTC',
      agentEnabled: (process.env.AGENT_ENABLED || 'false').toLowerCase() === 'true',
      agentName: process.env.AGENT_NAME || 'Bob',
    };
  }

  if (pathname === '/api/channels') {
    const all = channelManager.getAllTokens();
    return {
      channels: all.map(c => ({
        name: c.channelName, code: c.channelCode, source: c.source
      }))
    };
  }

  if (pathname === '/api/modlog') {
    const logs = modLogs.getAll(50);
    return { logs };
  }

  if (pathname === '/api/users') {
    const top     = users.getLeaderboard(50);
    const total   = db.prepare('SELECT COUNT(*) as c FROM users').get();
    const totalXp = db.prepare('SELECT SUM(xp) as x FROM users').get();
    const achiev  = db.prepare('SELECT COUNT(*) as c FROM user_achievements').get();
    return {
      leaderboard: top,
      totalUsers:  total?.c || 0,
      totalXp:     totalXp?.x || 0,
      totalAchievements: achiev?.c || 0,
    };
  }

  if (pathname === '/api/calendar') {
    const events = calendar.getUpcoming(50);
    // Enrich with notification status
    const enriched = events.map(e => {
      const notifs = db.prepare(
        'SELECT * FROM event_notifications WHERE event_id = ? ORDER BY notify_at'
      ).all(e.id);
      const rsvps = calendar.getRsvps(e.id);
      return { ...e, notifications: notifs, rsvpCount: rsvps.length };
    });
    return { events: enriched };
  }

  if (pathname === '/api/rss') {
    const feeds = rssFeeds.getAll();
    return {
      feeds: feeds.map(f => {
        const seenCount = db.prepare('SELECT COUNT(*) as c FROM rss_seen WHERE feed_id = ?').get(f.id);
        const lastItem  = db.prepare('SELECT item_title, seen_at FROM rss_seen WHERE feed_id = ? ORDER BY seen_at DESC LIMIT 1').get(f.id);
        return {
          ...f,
          channelName: channelManager.getChannelName(f.channel_id) || f.channel_id,
          seenCount:   seenCount?.c || 0,
          lastItemTitle: lastItem?.item_title || null,
          lastItemAt:    lastItem?.seen_at    || null,
        };
      })
    };
  }

  if (pathname === '/api/agent') {
    try {
      const agentDb = require('../agent/database').getDb();
      if (!agentDb) return { enabled: false };

      const convCount  = agentDb.prepare('SELECT COUNT(*) as c FROM conversations').get();
      const memCount   = agentDb.prepare('SELECT COUNT(*) as c FROM memory').get();
      const toolCount  = agentDb.prepare('SELECT COUNT(*) as c FROM tool_log').get();
      const toolStats  = agentDb.prepare(
        'SELECT tool_name, COUNT(*) as count FROM tool_log GROUP BY tool_name ORDER BY count DESC'
      ).all();
      const recentTools = agentDb.prepare(
        'SELECT tool_name, arguments, result, timestamp FROM tool_log ORDER BY timestamp DESC LIMIT 20'
      ).all();
      const channelConvs = agentDb.prepare(
        'SELECT channel_id, COUNT(*) as count FROM conversations GROUP BY channel_id ORDER BY count DESC'
      ).all();
      const digestStats = agentDb.prepare('SELECT * FROM rss_digests WHERE active = 1').all();

      return {
        enabled:      true,
        agentName:    process.env.AGENT_NAME || 'Bob',
        model:        process.env.OLLAMA_MODEL || 'unknown',
        ollamaUrl:    process.env.OLLAMA_URL || '',
        searxngUrl:   process.env.SEARXNG_URL || '',
        totalConversations: convCount?.c || 0,
        totalMemories:      memCount?.c  || 0,
        totalToolCalls:     toolCount?.c || 0,
        toolStats,
        recentTools,
        channelConversations: channelConvs.map(c => ({
          channelName: channelManager.getChannelName(c.channel_id) || c.channel_id,
          count: c.count,
        })),
        digests: digestStats,
      };
    } catch {
      return { enabled: false };
    }
  }

  if (pathname === '/api/settings') {
    const settingsKeys = [
      'BOT_NAME', 'TIMEZONE', 'HELP_DELETE_SECONDS',
      'ADMIN_DELETE_SECONDS', 'USER_DELETE_SECONDS',
      'RSS_CHECK_INTERVAL', 'RSS_MAX_ITEMS',
    ];
    // Load from DB overrides first, fall back to process.env
    let dbSettings = {};
    try {
      const rows = db.prepare('SELECT key, value FROM bot_settings WHERE key != ?').all('cmd_reg_hash');
      rows.forEach(r => { dbSettings[r.key] = r.value; });
    } catch {}
    const settings = {};
    for (const key of settingsKeys) {
      settings[key] = dbSettings[key] ?? process.env[key] ?? '';
    }
    return { settings };
  }

  if (pathname === '/api/health') {

    const pingOllama = () => new Promise(resolve => {
      const start = Date.now();
      const url   = new URL('/api/tags', process.env.OLLAMA_URL || 'http://localhost:11434');
      const lib   = url.protocol === 'https:' ? https : http;
      const req   = lib.get(url.toString(), res => {
        res.resume();
        resolve({ ok: res.statusCode === 200, ms: Date.now() - start });
      });
      req.on('error', () => resolve({ ok: false, ms: Date.now() - start }));
      req.setTimeout(3000, () => { req.destroy(); resolve({ ok: false, ms: 3000, error: 'timeout' }); });
    });

    const pingSearxng = () => new Promise(resolve => {
      if (!process.env.SEARXNG_URL) return resolve({ ok: false, disabled: true });
      const start = Date.now();
      const url   = new URL('/search?q=test&format=json', process.env.SEARXNG_URL);
      const lib   = url.protocol === 'https:' ? https : http;
      const req   = lib.get(url.toString(), { headers: { Accept: 'application/json' } }, res => {
        res.resume();
        resolve({ ok: res.statusCode === 200, ms: Date.now() - start });
      });
      req.on('error', () => resolve({ ok: false, ms: Date.now() - start }));
      req.setTimeout(3000, () => { req.destroy(); resolve({ ok: false, ms: 3000, error: 'timeout' }); });
    });

    const [ollama, searxng] = await Promise.all([pingOllama(), pingSearxng()]);
    return {
      ollama: { ...ollama, url: process.env.OLLAMA_URL || 'http://localhost:11434' },
      searxng,
      bot: { ok: true, uptime: Math.floor(process.uptime()) },
    };
  }

  return null;
}

// ---------------------------------------------------------------------------
// Write API handlers
// ---------------------------------------------------------------------------

async function handleWriteApi(pathname, method, payload, session, bot, channelManager) {
  const { calendar, rssFeeds, bans, db: botDb } = require('../database');
  const tz = process.env.TIMEZONE || 'UTC';

  // ── Calendar ────────────────────────────────────────────────────────────────

  if (pathname === '/api/calendar' && method === 'POST') {
    const { title, date, time, notify } = payload;
    if (!title || !date || !time) return { error: 'title, date and time are required' };

    const combined = `${date}T${time}:00`;
    const eventUtc = new Date(combined).toISOString();
    if (new Date(eventUtc) <= new Date()) return { error: 'Event date must be in the future' };

    const eventId = calendar.createEvent(title, eventUtc, payload.channel_id || null, session.username);

    // Add notifications
    const offsets = notify || ['1d', '6h', '30m'];
    const parseOffset = o => {
      const n = parseInt(o); const u = o.slice(-1);
      if (u === 'd') return n * 86400000;
      if (u === 'h') return n * 3600000;
      if (u === 'm') return n * 60000;
      return 0;
    };
    const eventTime = new Date(eventUtc);
    for (const offset of offsets) {
      const ms = parseOffset(offset);
      if (!ms) continue;
      const notifyAt = new Date(eventTime.getTime() - ms);
      if (notifyAt > new Date()) {
        const sqliteDate = notifyAt.toISOString().replace('T', ' ').replace(/\.\d+Z$/, '');
        calendar.addNotification(eventId, sqliteDate, offset);
      }
    }
    return { ok: true, id: eventId, message: `Event "${title}" created` };
  }

  if (pathname.startsWith('/api/calendar/') && method === 'DELETE') {
    const id = parseInt(pathname.split('/').pop());
    if (isNaN(id)) return { error: 'Invalid event ID' };
    botDb.prepare('DELETE FROM event_notifications WHERE event_id = ?').run(id);
    botDb.prepare('DELETE FROM event_rsvps WHERE event_id = ?').run(id);
    botDb.prepare('DELETE FROM events WHERE id = ?').run(id);
    return { ok: true, message: `Event #${id} deleted` };
  }

  if (pathname.startsWith('/api/calendar/') && method === 'POST') {
    const id = parseInt(pathname.split('/').pop());
    if (isNaN(id)) return { error: 'Invalid event ID' };
    const { title, date, time } = payload;
    if (!title && !date && !time) return { error: 'Nothing to update' };
    if (title) botDb.prepare('UPDATE events SET title = ? WHERE id = ?').run(title, id);
    if (date && time) {
      const eventUtc = new Date(`${date}T${time}:00`).toISOString().replace('T', ' ').replace(/\.\d+Z$/, '');
      botDb.prepare('UPDATE events SET event_time = ? WHERE id = ?').run(eventUtc, id);
    }
    return { ok: true, message: `Event #${id} updated` };
  }

  // ── RSS ──────────────────────────────────────────────────────────────────────

  if (pathname === '/api/rss' && method === 'POST') {
    const { url, channel_id, filter } = payload;
    if (!url) return { error: 'URL is required' };
    try {
      const result = rssFeeds.add(url, session.username, filter || null, channel_id || null);
      return { ok: true, id: result.lastInsertRowid, message: `Feed added` };
    } catch (err) {
      return { error: err.message };
    }
  }

  if (pathname.startsWith('/api/rss/') && method === 'DELETE') {
    const id = parseInt(pathname.split('/').pop());
    if (isNaN(id)) return { error: 'Invalid feed ID' };
    rssFeeds.remove(id);
    return { ok: true, message: `Feed #${id} removed` };
  }

  if (pathname.startsWith('/api/rss/') && method === 'POST') {
    const id = parseInt(pathname.split('/').pop());
    if (isNaN(id)) return { error: 'Invalid feed ID' };
    const { action } = payload;
    if (action === 'pause') {
      botDb.prepare('UPDATE rss_feeds SET active = 0 WHERE id = ?').run(id);
      return { ok: true, message: `Feed #${id} paused` };
    }
    if (action === 'resume') {
      botDb.prepare('UPDATE rss_feeds SET active = 1 WHERE id = ?').run(id);
      return { ok: true, message: `Feed #${id} resumed` };
    }
    return { error: 'Unknown action' };
  }

  // ── Channels ─────────────────────────────────────────────────────────────────

  if (pathname === '/api/channels' && method === 'POST') {
    const { name, code, token } = payload;
    if (!name || !code || !token) return { error: 'name, code and token are required' };
    if (code.length !== 8) return { error: 'Channel code must be 8 characters' };
    try {
      await channelManager.addChannel(name, code, token, session.username, bot);
      return { ok: true, message: `Channel "${name}" added` };
    } catch (err) {
      return { error: err.message };
    }
  }

  if (pathname.startsWith('/api/channels/') && method === 'DELETE') {
    const code = pathname.split('/').pop();
    const removed = channelManager.removeChannel(code);
    if (!removed) return { error: 'Channel not found or is an env-configured channel' };
    return { ok: true, message: `Channel ${code} removed` };
  }

  // ── Settings ─────────────────────────────────────────────────────────────────

  if (pathname === '/api/settings' && method === 'POST') {
    const allowed = [
      'BOT_NAME', 'TIMEZONE', 'HELP_DELETE_SECONDS',
      'ADMIN_DELETE_SECONDS', 'USER_DELETE_SECONDS',
      'RSS_CHECK_INTERVAL', 'RSS_MAX_ITEMS',
    ];
    const updates = {};
    for (const key of allowed) {
      if (payload[key] !== undefined) updates[key] = String(payload[key]);
    }
    if (Object.keys(updates).length === 0) return { error: 'No valid settings provided' };

    // Persist to bot_settings table
    try {
      botDb.prepare(`CREATE TABLE IF NOT EXISTS bot_settings (
        key TEXT PRIMARY KEY, value TEXT, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
      )`).run();
      for (const [key, value] of Object.entries(updates)) {
        botDb.prepare('INSERT OR REPLACE INTO bot_settings (key, value) VALUES (?, ?)').run(key, value);
        process.env[key] = value; // apply immediately without restart
      }
    } catch (err) {
      return { error: err.message };
    }
    return { ok: true, message: `${Object.keys(updates).length} setting(s) updated`, updates };
  }

  if (pathname === '/api/settings' && method === 'GET') {
    // Handled by getApiData — shouldn't reach here
    return null;
  }

  // ── Moderation ───────────────────────────────────────────────────────────────

  if (pathname.startsWith('/api/modlog/unban/') && method === 'POST') {
    const userId = pathname.split('/').pop();
    if (!userId) return { error: 'User ID required' };
    botDb.prepare('UPDATE bans SET active = 0 WHERE user_id = ?').run(userId);
    return { ok: true, message: `User ${userId} unbanned` };
  }

  return null;
}

// ---------------------------------------------------------------------------
// Static file server
// ---------------------------------------------------------------------------

const MIME_TYPES = {
  '.html': 'text/html',
  '.css':  'text/css',
  '.js':   'application/javascript',
  '.json': 'application/json',
  '.png':  'image/png',
  '.ico':  'image/x-icon',
  '.svg':  'image/svg+xml',
};

function serveStatic(res, filePath) {
  const ext  = path.extname(filePath);
  const mime = MIME_TYPES[ext] || 'text/plain';
  try {
    const content = fs.readFileSync(filePath);
    res.writeHead(200, { 'Content-Type': mime });
    res.end(content);
  } catch {
    res.writeHead(404);
    res.end('Not found');
  }
}

// ---------------------------------------------------------------------------
// Main server
// ---------------------------------------------------------------------------

function startDashboard(bot, channelManager) {
  if (!DASHBOARD_SECRET) {
    console.warn('⚠️  Dashboard disabled — DASHBOARD_SECRET not set in .env');
    console.warn('   Generate one with: openssl rand -base64 48');
    return null;
  }

  const staticDir = path.join(__dirname, 'public');

  const server = http.createServer(async (req, res) => {
    const reqUrl   = new URL(req.url, 'http://localhost');
    const pathname = reqUrl.pathname;
    const method   = req.method;

    // CORS headers for local dev
    res.setHeader('X-Content-Type-Options', 'nosniff');

    // --- Login token exchange ---
    if (pathname === '/auth/login' && method === 'POST') {
      let body = '';
      req.on('data', c => body += c);
      req.on('end', () => {
        try {
          const { token } = JSON.parse(body);
          const sessionSigned = redeemLoginToken(token);
          if (!sessionSigned) {
            res.writeHead(401, { 'Content-Type': 'application/json' });
            return res.end(JSON.stringify({ error: 'Invalid or expired token' }));
          }
          res.writeHead(200, {
            'Content-Type': 'application/json',
            'Set-Cookie': `dashboard_session=${encodeURIComponent(sessionSigned)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400`,
          });
          res.end(JSON.stringify({ ok: true }));
        } catch {
          res.writeHead(400);
          res.end('Bad request');
        }
      });
      return;
    }

    // --- Logout ---
    if (pathname === '/auth/logout' && method === 'POST') {
      res.writeHead(200, {
        'Content-Type': 'application/json',
        'Set-Cookie': 'dashboard_session=; HttpOnly; Path=/; Max-Age=0',
      });
      return res.end(JSON.stringify({ ok: true }));
    }

    // --- API routes (require auth) ---
    if (pathname.startsWith('/api/')) {
      const session = validateSession(req.headers.cookie);
      if (!session) {
        res.writeHead(401, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: 'Unauthorized' }));
      }

      // POST/DELETE write actions
      if (method === 'POST' || method === 'DELETE') {
        let body = '';
        req.on('data', c => body += c);
        await new Promise(resolve => req.on('end', resolve));
        let payload = {};
        try { payload = body ? JSON.parse(body) : {}; } catch {}

        const result = await handleWriteApi(pathname, method, payload, session, bot, channelManager);
        if (result === null) {
          res.writeHead(404, { 'Content-Type': 'application/json' });
          return res.end(JSON.stringify({ error: 'Not found' }));
        }
        const status = result.error ? 400 : 200;
        res.writeHead(status, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify(result));
      }

      // GET read actions
      const data = await getApiData(pathname, session, bot, channelManager);
      if (data === null) {
        res.writeHead(404, { 'Content-Type': 'application/json' });
        return res.end(JSON.stringify({ error: 'Not found' }));
      }
      res.writeHead(200, { 'Content-Type': 'application/json' });
      return res.end(JSON.stringify(data));
    }

    // --- Static files ---
    // Serve login page without auth
    if (pathname === '/' || pathname === '/login') {
      const session = validateSession(req.headers.cookie);
      if (session && pathname === '/login') {
        res.writeHead(302, { Location: '/dashboard' });
        return res.end();
      }
      if (!session && pathname !== '/login') {
        res.writeHead(302, { Location: '/login' });
        return res.end();
      }
      return serveStatic(res, path.join(staticDir, pathname === '/login' ? 'login.html' : 'index.html'));
    }

    // All other routes require auth
    const session = validateSession(req.headers.cookie);
    if (!session) {
      res.writeHead(302, { Location: '/login' });
      return res.end();
    }

    // Serve dashboard pages
    if (pathname === '/dashboard' || pathname === '/dashboard/') {
      return serveStatic(res, path.join(staticDir, 'index.html'));
    }

    // Serve static assets
    const filePath = path.join(staticDir, pathname.replace(/^\//, ''));
    serveStatic(res, filePath);
  });

  server.listen(DASHBOARD_PORT, () => {
    console.log(`🌐 Dashboard running at http://localhost:${DASHBOARD_PORT}`);
  });

  return server;
}

module.exports = { startDashboard, createLoginToken };
