const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function ask(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

async function main() {
  console.log('\n🤖 Haven Bot Setup Wizard\n');
  console.log('---\n');

  // Server URL
  const serverUrl = await ask('Haven server URL (e.g., https://your-server.com): ') || 'https://your-server.com';

  // Webhook Token
  const webhookToken = await ask('Webhook Token (64-char hex string): ') || '';

  // Callback URL
  const callbackUrl = await ask('Callback URL (optional, press Enter to skip): ') || '';

  // Callback Secret
  const callbackSecret = await ask('Callback secret (for HMAC verification): ') || '';

  // Bot Name
  const botName = await ask('Bot display name: ') || 'HavenBot';

  // Bot Avatar
  const botAvatar = await ask('Bot avatar URL (optional, press Enter to skip): ') || '';

  // Port
  const port = await ask('Callback server port: ') || '3000';

  // Debug
  const debug = await ask('Enable debug logging? (y/n): ') || 'n';

  rl.close();

  // Create .env file
  const envContent = `# Haven Bot Configuration
# Generated by setup wizard

# Server URL
HAVEN_SERVER_URL=${serverUrl}

# Bot Webhook Token
WEBHOOK_TOKEN=${webhookToken}

# Callback URL for slash command events
CALLBACK_URL=${callbackUrl || ''}

# Callback secret for HMAC verification
CALLBACK_SECRET=${callbackSecret || ''}

# Bot display name
BOT_NAME=${botName}

# Bot avatar URL
BOT_AVATAR_URL=${botAvatar || ''}

# Callback server port
PORT=${port}

# Enable debug logging
DEBUG=${debug.toLowerCase() === 'y' ? 'true' : 'false'}
`;

  fs.writeFileSync(path.join(__dirname, '..', '.env'), envContent);
  console.log('\n✅ .env file created successfully!');
  console.log('\n---\n');
  console.log('Next steps:');
  console.log('1. Review your .env file and make sure all values are correct');
  console.log('2. Run: npm start');
  console.log('');
}

main().catch(console.error);
